## The second In-class-exercise (09/22/2022, 40 points in total)

The purpose of this exercise is to understand users' information needs, then collect data from different sources for analysis.

Question 1 (10 points): Describe an interesting research question (or practical question) you have in mind, what kind of data should be collected to answer the question(s)? How many data needed for the analysis? The detail steps for collecting and save the data.

In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Please write you answer here:
Practical Question:
I like to ckeck the reviews of my favorite NIKE Revolution 5 Running Shoes so that i can deside weather to buy it or not.
Here i will review the ratings and also comments of the customers who allready buy this shoes.
Data:
i'm using one of the famous online shoping website which contains of nearly 1000 individual reviews.
we can analyze this user reviews by words and rating out of 5 .
Collecting and Save the Data:
importing library BeautifulSoup from bs4 for the information extraction from the website.
here we use web scraping for scraping the data
finally we can see the data set which have been processed 

'''

Question 2 (10 points): Write python code to collect 1000 data samples you discussed above.

In [2]:
# You code here (Please add comments in the code):
import requests
from bs4 import BeautifulSoup
import pandas as pd
main_text = [] # List to store Review headings
sub_text =[] #List to store reviews

#Collected the Nike Revolution 5 Running shoew review page link
for number in range(100):
  requested_link = "https://www.flipkart.com/nike-revolution-5-running-shoes-men/product-reviews/itm11637de31a718?pid=SHOFK455USFFYRMG&lid=LSTSHOFK455USFFYRMGWHZANI&marketplace=FLIPKART" + str(number) # Generating link dynamically
  #Getting Request for the link above
  web_page = requests.get(requested_link)
  soup = BeautifulSoup(web_page.text, 'html.parser')
  rating_reviews = soup.find_all(class_='_3LWZlK _1BLPMq _3B8WaH')
  text_reviews = soup.find_all(class_='col _2wzgFH K0kLPL _1QgsS5')
  for ele, sub_ele in zip(rating_reviews, text_reviews) : # Iterating through the list
      main_text.append(ele.text) #Appending to empty list
      sub_text.append(sub_ele.text)

#Dataframe Creation by combining collected data and making the column names of our own!
Nike_Reviews = pd.DataFrame(list(zip(main_text, sub_text)), columns =['Rating', 'Glimpse of Review']) 
print("Obtained Data Frame Length is {0}".format(len(Nike_Reviews)))
Nike_Reviews

Obtained Data Frame Length is 1000

    Rating                                  Glimpse of Review
0        5  5PerfectREAD MOREDebasish Haloi11 months ago18...
1        4  4Shoes are genuine...today i got my pair ..the...
2        5  5Very nice shoeREAD MOREAJAY KUMAR  SHARMAMay,...
3        5  5comfort at his very best ...good shoes for ru...
4        5  5Worth it...!!!Very light weighted and perfect...
..     ...                                                ...
995      5  5Mast quality....!!!READ MOREAyan  MeheraSep, ...
996      5  5Very nice shoes at affordable price and its o...
997      5  5Excellent quality, Very comfortable, nice loo...
998      5  5Nice product ðŸ‘ŒREAD MOREMukesh ThakorMar, 2020...
999      5  5cool look comfort fit lightweight shoesðŸ”¥READ ...

[1000 rows x 2 columns]

Question 3 (10 points): Write python code to collect 1000 articles from Google Scholar (https://scholar.google.com/), Microsoft Academic (https://academic.microsoft.com/home), or CiteSeerX (https://citeseerx.ist.psu.edu/index), or Semantic Scholar (https://www.semanticscholar.org/), or ACM Digital Libraries (https://dl.acm.org/) with the keyword "information retrieval". The articles should be published in the last 10 years (2012-2022).

The following information of the article needs to be collected:

(1) Title

(2) Venue/journal/conference being published

(3) Year

(4) Authors

(5) Abstract

In [42]:
# You code here (Please add comments in the code):
from bs4 import BeautifulSoup#importing python packag Beautifulsoup
import requests, lxml, os, json
import pandas as pd#importing pandas
headers = {
    'User-agent':
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/70.0.3538.102 Safari/537.36 Edge/18.19582"
}
params = {
  "q": "Information Science",
  "hl": "en",
}
google_link = requests.get('https://scholar.google.com/scholar', headers=headers, params = params).text#here we did for google scholar
soup = BeautifulSoup(google_link, 'lxml')
for pdf in soup.select('.gs_or_ggsm a'):
  pdf_file_link = pdf['href']
  print(pdf_file_link)
  data = []
for result in soup.select('.gs_ri'):
  T_header = result.select_one('.gs_rt').text
  publication_info = result.select_one('.gs_a').text
  abstract = result.select_one('.gs_rs').text
  try:
    version_of_articles = result.select_one('a~ a+ .gs_nph')['href']
  except:
    version_of_articles = None
  d = {
      'TITLE': T_header,'Authors,Venue,journal,conference,Year': publication_info,'ABSTRACT': abstract
  }
  data.append(d)
data_frame = pd.DataFrame(data)
data_frame.head()
#reff https://dev.to/dmitryzub/scrape-google-scholar-with-python-32oh

https://www.marilia.unesp.br/Home/Instituicao/Docentes/EdbertoFerneda/k---artigo-01.pdf
https://www.academia.edu/download/30771284/relevanceSaracevic.pdf
https://discovery.ucl.ac.uk/id/eprint/10053533/3/Longley_version%202.0_Manfred%20geocomp_PAL.pdf
http://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.199.7788&rep=rep1&type=pdf

,TITLE,"Authors,Venue,journal,conference,Year",ABSTRACT
0,Information science: what is it?,"H BorkoÂ - American documentation, 1968 - Wiley...",â€¦ the American Society for Information Science...
1,The foundations of information science. Part I...,"BC BrookesÂ - Journal of information science, 1...",â€¦ It is first argued that a niche for informat...
2,Information concepts for information science,"NJ BelkinÂ - Journal of documentation, 1978 - e...","â€¦ , to problems within the theoretical structu..."
3,[BOOK][B] Foundations of library and informati...,RE Rubin - 2017 - books.google.com,â€¦ tensions in LIS education between informatio...
4,Relevance: A review of and a framework for the...,T SaracevicÂ - â€¦Â of the American Society for in...,â€¦ -line information â€¦ information systems is s...

Question 4 (10 points): Write python code to collect 1000 posts from Twitter, or Facebook, or Instagram. You can either use hashtags, keywords, user_name, user_id, or other information to collect the data. 

The following information needs to be collected:

(1) User_name

(2) Posted time

(3) Text

In [29]:
# You code here (Please add comments in the code):
import os#importing the necessary Python libraries
import tweepy as tw
import pandas as pd
import numpy as np
from tweepy import OAuthHandler
import requests
import json
#First you will define keys
customer_key ="2Em7SxlX9jPMfL4x97r3zMO0x"
customer_secret = "sVbJzekKuiAgq83Y7gCwNVbSowqQokGVzWexKHl2cXIPceWtSd"
access_token ="1439767876962029572-uUMt8oWRyzj9ilE5zk4uYbL93sCMPT"
access_token_secret = "oydIGymn9bS767FVEMawE9GyGAnMmBJfaY2XXKmHnmliF"
auth = tw.OAuthHandler(customer_key, customer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tw.API(auth,wait_on_rate_limit=True)
username =str(input("Enter user name\t"))
tweets_ex = tw.Cursor(api.user_timeline,id=username).items(1000)
tweets_list_ex = [[username ,tweet.created_at, tweet.text] for tweet in tweets_ex]
tweets_ex_df = pd.DataFrame(tweets_list_ex)#create a pandas dataframe that contains that data.
tweets_ex_df.columns=['User_name','Posted time','text']
tweets_ex_df#Twitter will return all tweets that contain the given word

Enter user name	jtntr

  User_name         Posted time                     text
0     jtntr 2017-11-18 07:42:13  https://t.co/AiCZ7z2hXW
1     jtntr 2017-11-17 16:42:19  https://t.co/AywnUmVMIU
2     jtntr 2017-11-17 16:41:31  https://t.co/Ot6ROcGkZG
3     jtntr 2017-11-17 16:41:10  https://t.co/ENKXBVb5lc
4     jtntr 2017-11-17 16:40:44  https://t.co/ttaXp4ssE3
5     jtntr 2017-11-15 06:39:41  https://t.co/2aR7rzQzju
6     jtntr 2017-11-15 06:35:08  https://t.co/acrjSvPmD9