## The third In-class-exercise (10/06/2022, 40 points in total)

The purpose of this exercise is to understand text representation.

Question 1 (10 points): Describe an interesting text classification or text mining task and explain what kind of features might be useful for you to build the machine learning model. List your features and explain why these features might be helpful. You need to list at least five different types of features.

In [ ]:
# Your answer here (no code for this question, write down your answer as detail as possible for the above questions):

'''
Text classification is one of the key problems in machine learning that helps us organize and analyze text by automatically categorizing texts.

A text classifier can analyze, comprehend, organize, and order textual data to take a sentence as input and automatically give the proper labels.

On a sample set of text data, I wish to carry out text mining and extraction operations. Utilizing feature extraction operations and measuring particular data features helps reduce the dimensions of the data. Following operations performed as part of text mining anf extraction operations

Feature extraction operations : Number of sentences, Number of words, NUmber of characters, Number of stopwords, number of special characters, Number of numerics, and Number of uppercase words
Text mining operations : Lower casing, Punctuation removal, Stopwords removal, Frequent words removal, Rare words removal, Spelling corrections, Stemming



'''

Question 2 (20 points): Write python code to extract these features you discussed above. You can collect a few sample text data for the feature extraction.

In [ ]:
# You code here (Please add comments in the code):
import pandas as pd

text_file="http://www.textfiles.com/adventure/abyssal.txt"
text=pd.read_csv(text_file,error_bad_lines=False,names=['lines'])
text.head(10)

/usr/local/lib/python3.7/dist-packages/IPython/core/interactiveshell.py:3326: FutureWarning: The error_bad_lines argument has been deprecated and will be removed in a future version.


  exec(code_obj, self.user_global_ns, self.user_ns)

                                               lines
0          ADVENTURE SOLVE FOR: >>> ABYSSAL ZONE <<<
1                            I HAVE TRIED MANY TIMES
2      BUT THERE APPEARS TO BE NO WAY TO GET MORE...
3                 SOLVER WILL TAKE YOU TO THAT PIONT
4      IF ANYONE CAN THEN FIGURE OUT HOW TO GET M...
5                                           TUTORIAL
6      YOU MUST DO THERE IS JUST NOT ENOUGH AIR.....
7  :.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:....
8       YOU START OUT ON AN UNSTABLE VOLCANIC ISLAND
9                WE WILL TRY TO GET YOU OUT SAFELY..

In [ ]:
# Num of sentences

text['Num of Sentences'] = text['lines'].apply(lambda x: len(str(x).split(".")))

text[['lines','Num of Sentences']]

                                                lines  Num of Sentences
0           ADVENTURE SOLVE FOR: >>> ABYSSAL ZONE <<<                 1
1                             I HAVE TRIED MANY TIMES                 1
2       BUT THERE APPEARS TO BE NO WAY TO GET MORE...                 1
3                  SOLVER WILL TAKE YOU TO THAT PIONT                 1
4       IF ANYONE CAN THEN FIGURE OUT HOW TO GET M...                 1
5                                            TUTORIAL                 1
6       YOU MUST DO THERE IS JUST NOT ENOUGH AIR.....                 9
7   :.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:....                39
8        YOU START OUT ON AN UNSTABLE VOLCANIC ISLAND                 1
9                 WE WILL TRY TO GET YOU OUT SAFELY..                 3
10                                          READ SIGN                 1
11                                        GET FEATHER                 1
12                                                  E                 1
13      YOU ARE NOW ON THE REEF SURROUNDING THE MA...                 1
14                                  TRIANGLE AREA....                 5
15                                                  N                 1
16                                   LOOK VASE-SPONGE                 1
17                                                  E                 1
18      THAT TAKES CARE OF THAT SECTION.. NOW WE'R...                 5
19                                                  N                 1
20                                                  N                 1
21                                                  N                 1
22                                            GET CAN                 1
23                          NOW INTO THE CITY AREA...                 4
24                                                  W                 1
25                                      PLAY RECORDER                 1
26   => THIS IS WHERE OUR AIR SUPPLY RUNS OUT! IF ...                 1
27                              HELP THEM GET FARTHER                 1
28                                      IT'S POSSIBLE                 1

In [ ]:
# Num of Words

text['No of Words']=text['lines'].apply(lambda x: len(x.split(" ")))

text[['lines','No of Words']]

                                                lines  No of Words
0           ADVENTURE SOLVE FOR: >>> ABYSSAL ZONE <<<            7
1                             I HAVE TRIED MANY TIMES            9
2       BUT THERE APPEARS TO BE NO WAY TO GET MORE...           18
3                  SOLVER WILL TAKE YOU TO THAT PIONT           11
4       IF ANYONE CAN THEN FIGURE OUT HOW TO GET M...           15
5                                            TUTORIAL            5
6       YOU MUST DO THERE IS JUST NOT ENOUGH AIR.....           13
7   :.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:....            1
8        YOU START OUT ON AN UNSTABLE VOLCANIC ISLAND           12
9                 WE WILL TRY TO GET YOU OUT SAFELY..           12
10                                          READ SIGN            6
11                                        GET FEATHER            6
12                                                  E            5
13      YOU ARE NOW ON THE REEF SURROUNDING THE MA...           18
14                                  TRIANGLE AREA....            6
15                                                  N            5
16                                   LOOK VASE-SPONGE            6
17                                                  E            5
18      THAT TAKES CARE OF THAT SECTION.. NOW WE'R...           16
19                                                  N            5
20                                                  N            5
21                                                  N            5
22                                            GET CAN            6
23                          NOW INTO THE CITY AREA...            9
24                                                  W            5
25                                      PLAY RECORDER            6
26   => THIS IS WHERE OUR AIR SUPPLY RUNS OUT! IF ...           17
27                              HELP THEM GET FARTHER            8
28                                      IT'S POSSIBLE            6

In [ ]:
# Num of Characters

text['Num of Characters'] = text['lines'].str.len()
text[['lines','Num of Characters']]

                                                lines  Num of Characters
0           ADVENTURE SOLVE FOR: >>> ABYSSAL ZONE <<<                 41
1                             I HAVE TRIED MANY TIMES                 27
2       BUT THERE APPEARS TO BE NO WAY TO GET MORE...                 65
3                  SOLVER WILL TAKE YOU TO THAT PIONT                 38
4       IF ANYONE CAN THEN FIGURE OUT HOW TO GET M...                 53
5                                            TUTORIAL                 12
6       YOU MUST DO THERE IS JUST NOT ENOUGH AIR.....                 52
7   :.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:....                 77
8        YOU START OUT ON AN UNSTABLE VOLCANIC ISLAND                 48
9                 WE WILL TRY TO GET YOU OUT SAFELY..                 39
10                                          READ SIGN                 13
11                                        GET FEATHER                 15
12                                                  E                  5
13      YOU ARE NOW ON THE REEF SURROUNDING THE MA...                 76
14                                  TRIANGLE AREA....                 21
15                                                  N                  5
16                                   LOOK VASE-SPONGE                 20
17                                                  E                  5
18      THAT TAKES CARE OF THAT SECTION.. NOW WE'R...                 71
19                                                  N                  5
20                                                  N                  5
21                                                  N                  5
22                                            GET CAN                 11
23                          NOW INTO THE CITY AREA...                 29
24                                                  W                  5
25                                      PLAY RECORDER                 17
26   => THIS IS WHERE OUR AIR SUPPLY RUNS OUT! IF ...                 77
27                              HELP THEM GET FARTHER                 25
28                                      IT'S POSSIBLE                 17

In [ ]:
# Num of Stopwords
from nltk.corpus import stopwords

import nltk
nltk.download('stopwords')
stop = stopwords.words('english')

text['Num of Stopwords'] = text['lines'].apply(lambda x: len([x for x in x.split() if x in stop]))
text[['lines','Num of Stopwords']]

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

                                                lines  Num of Stopwords
0           ADVENTURE SOLVE FOR: >>> ABYSSAL ZONE <<<                 0
1                             I HAVE TRIED MANY TIMES                 0
2       BUT THERE APPEARS TO BE NO WAY TO GET MORE...                 0
3                  SOLVER WILL TAKE YOU TO THAT PIONT                 0
4       IF ANYONE CAN THEN FIGURE OUT HOW TO GET M...                 0
5                                            TUTORIAL                 0
6       YOU MUST DO THERE IS JUST NOT ENOUGH AIR.....                 0
7   :.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:....                 0
8        YOU START OUT ON AN UNSTABLE VOLCANIC ISLAND                 0
9                 WE WILL TRY TO GET YOU OUT SAFELY..                 0
10                                          READ SIGN                 0
11                                        GET FEATHER                 0
12                                                  E                 0
13      YOU ARE NOW ON THE REEF SURROUNDING THE MA...                 0
14                                  TRIANGLE AREA....                 0
15                                                  N                 0
16                                   LOOK VASE-SPONGE                 0
17                                                  E                 0
18      THAT TAKES CARE OF THAT SECTION.. NOW WE'R...                 0
19                                                  N                 0
20                                                  N                 0
21                                                  N                 0
22                                            GET CAN                 0
23                          NOW INTO THE CITY AREA...                 0
24                                                  W                 0
25                                      PLAY RECORDER                 0
26   => THIS IS WHERE OUR AIR SUPPLY RUNS OUT! IF ...                 0
27                              HELP THEM GET FARTHER                 0
28                                      IT'S POSSIBLE                 0

In [ ]:
# Num of Special Characters

text['special character count']=text['lines'].apply(lambda x: len([y for y in x.split() if y.startswith(('#','@'))]))
text[['lines','special character count']]

                                                lines  special character count
0           ADVENTURE SOLVE FOR: >>> ABYSSAL ZONE <<<                        0
1                             I HAVE TRIED MANY TIMES                        0
2       BUT THERE APPEARS TO BE NO WAY TO GET MORE...                        0
3                  SOLVER WILL TAKE YOU TO THAT PIONT                        0
4       IF ANYONE CAN THEN FIGURE OUT HOW TO GET M...                        0
5                                            TUTORIAL                        0
6       YOU MUST DO THERE IS JUST NOT ENOUGH AIR.....                        0
7   :.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:....                        0
8        YOU START OUT ON AN UNSTABLE VOLCANIC ISLAND                        0
9                 WE WILL TRY TO GET YOU OUT SAFELY..                        0
10                                          READ SIGN                        0
11                                        GET FEATHER                        0
12                                                  E                        0
13      YOU ARE NOW ON THE REEF SURROUNDING THE MA...                        0
14                                  TRIANGLE AREA....                        0
15                                                  N                        0
16                                   LOOK VASE-SPONGE                        0
17                                                  E                        0
18      THAT TAKES CARE OF THAT SECTION.. NOW WE'R...                        0
19                                                  N                        0
20                                                  N                        0
21                                                  N                        0
22                                            GET CAN                        0
23                          NOW INTO THE CITY AREA...                        0
24                                                  W                        0
25                                      PLAY RECORDER                        0
26   => THIS IS WHERE OUR AIR SUPPLY RUNS OUT! IF ...                        0
27                              HELP THEM GET FARTHER                        0
28                                      IT'S POSSIBLE                        0

In [ ]:
# Num of Numerics

text['numeric count']=text['lines'].apply(lambda x: len([y for y in x.split() if y.isdigit()]))
text[['lines','numeric count']]

                                                lines  numeric count
0           ADVENTURE SOLVE FOR: >>> ABYSSAL ZONE <<<              0
1                             I HAVE TRIED MANY TIMES              0
2       BUT THERE APPEARS TO BE NO WAY TO GET MORE...              0
3                  SOLVER WILL TAKE YOU TO THAT PIONT              0
4       IF ANYONE CAN THEN FIGURE OUT HOW TO GET M...              0
5                                            TUTORIAL              0
6       YOU MUST DO THERE IS JUST NOT ENOUGH AIR.....              0
7   :.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:....              0
8        YOU START OUT ON AN UNSTABLE VOLCANIC ISLAND              0
9                 WE WILL TRY TO GET YOU OUT SAFELY..              0
10                                          READ SIGN              0
11                                        GET FEATHER              0
12                                                  E              0
13      YOU ARE NOW ON THE REEF SURROUNDING THE MA...              0
14                                  TRIANGLE AREA....              0
15                                                  N              0
16                                   LOOK VASE-SPONGE              0
17                                                  E              0
18      THAT TAKES CARE OF THAT SECTION.. NOW WE'R...              0
19                                                  N              0
20                                                  N              0
21                                                  N              0
22                                            GET CAN              0
23                          NOW INTO THE CITY AREA...              0
24                                                  W              0
25                                      PLAY RECORDER              0
26   => THIS IS WHERE OUR AIR SUPPLY RUNS OUT! IF ...              0
27                              HELP THEM GET FARTHER              0
28                                      IT'S POSSIBLE              0

In [ ]:
# Num of uppercase words

text['uppercase words']=text['lines'].apply(lambda x: len([y for y in x.split() if y.isupper()]))
text[['lines','uppercase words']]

                                                lines  uppercase words
0           ADVENTURE SOLVE FOR: >>> ABYSSAL ZONE <<<                5
1                             I HAVE TRIED MANY TIMES                5
2       BUT THERE APPEARS TO BE NO WAY TO GET MORE...               14
3                  SOLVER WILL TAKE YOU TO THAT PIONT                7
4       IF ANYONE CAN THEN FIGURE OUT HOW TO GET M...               11
5                                            TUTORIAL                1
6       YOU MUST DO THERE IS JUST NOT ENOUGH AIR.....                9
7   :.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:....                0
8        YOU START OUT ON AN UNSTABLE VOLCANIC ISLAND                8
9                 WE WILL TRY TO GET YOU OUT SAFELY..                8
10                                          READ SIGN                2
11                                        GET FEATHER                2
12                                                  E                1
13      YOU ARE NOW ON THE REEF SURROUNDING THE MA...               14
14                                  TRIANGLE AREA....                2
15                                                  N                1
16                                   LOOK VASE-SPONGE                2
17                                                  E                1
18      THAT TAKES CARE OF THAT SECTION.. NOW WE'R...               12
19                                                  N                1
20                                                  N                1
21                                                  N                1
22                                            GET CAN                2
23                          NOW INTO THE CITY AREA...                5
24                                                  W                1
25                                      PLAY RECORDER                2
26   => THIS IS WHERE OUR AIR SUPPLY RUNS OUT! IF ...               15
27                              HELP THEM GET FARTHER                4
28                                      IT'S POSSIBLE                2

In [ ]:
# Lower casing

text['lines']=text['lines'].str.lower()
text['lines']

0             adventure solve for: >>> abyssal zone <<<
1                               i have tried many times
2         but there appears to be no way to get more...
3                    solver will take you to that piont
4         if anyone can then figure out how to get m...
5                                              tutorial
6         you must do there is just not enough air.....
7     :.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:.:....
8          you start out on an unstable volcanic island
9                   we will try to get you out safely..
10                                            read sign
11                                          get feather
12                                                    e
13        you are now on the reef surrounding the ma...
14                                    triangle area....
15                                                    n
16                                     look vase-sponge
17                                                    e
18        that takes care of that section.. now we'r...
19                                                    n
20                                                    n
21                                                    n
22                                              get can
23                            now into the city area...
24                                                    w
25                                        play recorder
26     => this is where our air supply runs out! if ...
27                                help them get farther
28                                        it's possible
Name: lines, dtype: object

In [ ]:
# Punctuation removal

import string
text['lines']=text['lines'].str.replace('[{}]'.format(string.punctuation), '')
text['lines']

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: The default value of regex will change from True to False in a future version.
  after removing the cwd from sys.path.

0                    adventure solve for  abyssal zone
1                               i have tried many times
2         but there appears to be no way to get more...
3                    solver will take you to that piont
4         if anyone can then figure out how to get m...
5                                              tutorial
6              you must do there is just not enough air
7
8          you start out on an unstable volcanic island
9                     we will try to get you out safely
10                                            read sign
11                                          get feather
12                                                    e
13        you are now on the reef surrounding the ma...
14                                        triangle area
15                                                    n
16                                      look vasesponge
17                                                    e
18        that takes care of that section now were o...
19                                                    n
20                                                    n
21                                                    n
22                                              get can
23                               now into the city area
24                                                    w
25                                        play recorder
26      this is where our air supply runs out if any...
27                                help them get farther
28                                         its possible
Name: lines, dtype: object

In [ ]:
# Stopwords removal

from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')
stop=stopwords.words('english')

text['lines']=text['lines'].apply(lambda x:" ".join(x for x in x.split() if x not in stop))
text['lines']

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!

0                  adventure solve abyssal zone
1                              tried many times
2                appears way get air toward end
3                             solver take piont
4                         anyone figure get air
5                                      tutorial
6                               must enough air
7
8                start unstable volcanic island
9                                try get safely
10                                    read sign
11                                  get feather
12                                            e
13    reef surrounding many small island devils
14                                triangle area
15                                            n
16                              look vasesponge
17                                            e
18            takes care section abyssal planes
19                                            n
20                                            n
21                                            n
22                                          get
23                                    city area
24                                            w
25                                play recorder
26          air supply runs anyone use tutorial
27                             help get farther
28                                     possible
Name: lines, dtype: object

In [ ]:
# Frequent words removal

freq=pd.Series(' '.join(text['lines']).split()).value_counts()[:10]
freq=list(freq.index)

text['lines']=text['lines'].apply(lambda x:" ".join(x for x in x.split() if x not in freq))
text['lines']

0              adventure solve zone
1                       tried times
2            appears way toward end
3                 solver take piont
4                            figure
5
6                       must enough
7
8           start unstable volcanic
9                        try safely
10                        read sign
11                          feather
12
13    reef surrounding small devils
14                         triangle
15
16                  look vasesponge
17
18        takes care section planes
19
20
21
22
23                             city
24                                w
25                    play recorder
26                  supply runs use
27                     help farther
28                         possible
Name: lines, dtype: object

In [ ]:
# Rare words removal

rare=pd.Series(' '.join(text['lines']).split()).value_counts()[-10:]

rare=list(rare.index)
text['lines']=text['lines'].apply(lambda x:" ".join(x for x in x.split() if x not in rare))
text['lines']

0              adventure solve zone
1                       tried times
2            appears way toward end
3                 solver take piont
4
5
6
7
8
9
10                             sign
11                          feather
12
13    reef surrounding small devils
14                         triangle
15
16                  look vasesponge
17
18        takes care section planes
19
20
21
22
23                             city
24                                w
25                    play recorder
26                  supply runs use
27                     help farther
28
Name: lines, dtype: object

In [ ]:
# Spelling correction

from textblob import TextBlob

text['lines']=text['lines'].apply(lambda x: str(TextBlob(x).correct()))
text['lines']

0              adventure solve zone
1                       tried times
2            appears way toward end
3                 silver take point
4
5
6
7
8
9
10                             sign
11                          feather
12
13    reef surrounding small devils
14                         triangle
15
16                  look vasesponge
17
18        takes care section planes
19
20
21
22
23                             city
24                                w
25                    play recorder
26                  supply runs use
27                     help farther
28
Name: lines, dtype: object

In [ ]:
# Stemming

from nltk.stem import PorterStemmer
stemmer=PorterStemmer()

text['lines']=text['lines'].apply(lambda x: " ".join([stemmer.stem(word) for word in x.split()]))
text['lines']

0            adventur solv zone
1                      tri time
2         appear way toward end
3             silver take point
4
5
6
7
8
9
10                         sign
11                      feather
12
13    reef surround small devil
14                      triangl
15
16               look vasespong
17
18      take care section plane
19
20
21
22
23                         citi
24                            w
25                  play record
26               suppli run use
27                 help farther
28
Name: lines, dtype: object

Question 3 (10 points): Use any of the feature selection methods mentioned in this paper "Deng, X., Li, Y., Weng, J., & Zhang, J. (2019). Feature selection for text classification: A review. Multimedia Tools & Applications, 78(3)." Select the most important features you extracted above, rank the features based on their importance in the descending order.

In [ ]:
# You code here (Please add comments in the code):


term_freq = (text['lines'][1:2]).apply(lambda x: pd.value_counts(x.split(" "))).sum(axis = 0).reset_index()
term_freq.columns = ['words','term_freq']
term_freq

   words  term_freq
0                 4
1      I          1
2   HAVE          1
3  TRIED          1
4   MANY          1
5  TIMES          1

In [ ]:
import numpy as np

for i,word in enumerate(term_freq['words']):
    term_freq.loc[i, 'inverse doc freq'] = np.log(text.shape[0]/(len(text[text['lines'].str.contains(word)])))

term_freq

   words  term_freq  inverse doc freq
0                 4          0.000000
1      I          1          0.659246
2   HAVE          1          3.367296
3  TRIED          1          3.367296
4   MANY          1          2.674149
5  TIMES          1          3.367296

In [ ]:
#TF-IDF

term_freq['TF-IDF'] = term_freq['term_freq'] * term_freq['inverse doc freq']
term_freq

   words  term_freq  inverse doc freq    TF-IDF
0                 4          0.000000  0.000000
1      I          1          0.659246  0.659246
2   HAVE          1          3.367296  3.367296
3  TRIED          1          3.367296  3.367296
4   MANY          1          2.674149  2.674149
5  TIMES          1          3.367296  3.367296